# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  Say-Date:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Set the current hour as an environment variable"
          command: |
            TEST_HOUR=$(date +%H)
            echo "export JOB_HOUR=$TEST_HOUR" >> $BASH_ENV
      - run:
          name: "Use the TEST_HOUR variable"
          command: echo "$JOB_HOUR"
  
  Renew-Image: 
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Renewing Panel Image
          command: |
            CURRENT_HOUR=$(date +%H)
            if [ $CURRENT_HOUR -lt 2 ]; then
              cp DinnerPanel.png currentoutput.png
            elif [ $CURRENT_HOUR -lt 5 ]; then
              cp LateNightSnackPanel.png currentoutput.png
            elif [ $CURRENT_HOUR -lt 13 ]; then
              cp BedTimePanel.png currentoutput.png
            elif [ $CURRENT_HOUR -lt 18 ]; then
              cp BreakfastPanel.png currentoutput.png
            elif [ $CURRENT_HOUR -lt 21 ]; then
              cp LunchPanel.png currentoutput.png
            elif [ $CURRENT_HOUR -lt 23 ]; then
              cp SnackPanel.png currentoutput.png
            else
              cp DinnerPanel.png currentoutput.png
            fi
            cp LunchPanel.png testoutput.png
      - add_ssh_keys:
          fingerprints:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO5Gs08GZMcQUrtKG+0HxvHB9TLm8YQX7BXcyaaMCZew wanderingbark@gmail.com"
      - run:
          name: Committing Changes to Repo
          command: |
            git config user.email "wanderingbark@gmail.com"
            git config user.name "CircleCI Job"
            git add .
            git commit --allow-empty -m "Automatic commit from CircleCI [skip ci]"
            git push origin circleci-project-setup
    
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  Test1: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - Say-Date
      - Renew-Image
