name: Update Image By Time of Day
on:
  schedule:
      - cron: '0 * * * *' # Runs every hour
#    - cron: '0 2,5,12,17,20,23 * * *' 

#on: push

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Image
        run: |
          HOUR=$(date +%H)-6
          if [ $HOUR -lt 10 ]; then
            cp BreakfastPanel.png currentoutput.png
          elif [[ $HOUR -ge 10 && $HOUR -lt 12 ]]; then
            cp LunchPanel.png currentoutput.png
          elif [[ $HOUR -ge 13 && $HOUR -lt 17 ]]; then
            cp SnackPanel.png currentoutput.png
          elif [[ $HOUR -ge 17 && $HOUR -lt 20 ]]; then
            cp DinnerPanel.png currentoutput.png
          elif [[ $HOUR -ge 20 && $HOUR -lt 22 ]]; then
            cp LateNightSnackPanel.png currentoutput.png
          else
            cp BedtimePanel.png currentoutput.png
          fi
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currentoutput.png
          git commit -m "Update image based on time"
          git push
          echo test, and deploy your project.
