name: crontest

on:
  workflow_dispatch:
  schedule:
    - cron: '12 7,11,14,17 * * *'
      timezone: "America/Edmonton"

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job ran successfully!"
